analysis prefix-caching
Signed-off-by: Michael Kalantar <kalantar@us.ibm.com>

diff --git a/tekton/tasks/run-workload-inference-perf.yaml b/tekton/tasks/run-workload-inference-perf.yaml
--- a/tekton/tasks/run-workload-inference-perf.yaml
+++ b/tekton/tasks/run-workload-inference-perf.yaml
@@ -18,11 +18,14 @@ spec:
     - { name: profileTemplate, type: string }
     - { name: treatment, type: string }
     - { name: results_dir, type: string }
+    - { name: treatment_path, type: string }
 
   steps:
     - name: augment-treatment-overrides
       results:
         - { name: merged-overrides }
+      env:
+        - { name: LOCAL_STORAGE_PATH, value: "$(workspaces.data.path)/$(params.results_dir)/$(params.treatment_path)/results" }
       image: alpine/kubectl:1.34.1
       script: |
         #!/bin/sh
@@ -32,7 +35,7 @@ spec:
         echo "server.model_name=$(params.model)" >> $(step.results.merged-overrides.path)
         echo "server.base_url=$(params.url)" >> $(step.results.merged-overrides.path)
         echo "tokenizer.pretrained_model_name_or_path=$(params.model)" >> $(step.results.merged-overrides.path)
-        echo "storage.local_storage.path=$(workspaces.data.path)/$(params.results_dir)/$(params.modelLabel)" >> $(step.results.merged-overrides.path)
+        echo "storage.local_storage.path=${LOCAL_STORAGE_PATH}" >> $(step.results.merged-overrides.path)
 
     - name: apply-overrides
       ref:
@@ -55,6 +58,8 @@ spec:
     - name: run
       env:
         - { name: HARNESS, value: inference-perf }
+        - { name: RESULTS_DIR, value: "$(workspaces.data.path)/$(params.results_dir)/$(params.treatment_path)/experiments" }
+        - { name: WORKLOAD_PROFILE_DIR, value: "$(workspaces.data.path)/$(params.results_dir)/$(params.treatment_path)/profiles/inference-perf" }
       computeResources:
         requests:
           memory: "16Gi"
@@ -66,22 +71,26 @@ spec:
       script: |
         #!/usr/bin/env bash
 
-        RESULTS_DIR="$(workspaces.data.path)/$(params.results_dir)"
-        WORKLOAD_PROFILE=${RESULTS_DIR}/workload/profiles/${HARNESS}/profile.yaml
-        mkdir -p ${RESULTS_DIR}/workload/profiles/${HARNESS}
+        $ make sure target directories exist
+        mkdir -p $RESULTS_DIR
+        mkdir -p $WORKLOAD_PROFILE_DIR
+
+        # Copy profile from workspace to experiment results dir
+        WORKLOAD_PROFILE="${WORKLOAD_PROFILE_DIR}/profile.yaml"
         cp /workspace/output.yaml ${WORKLOAD_PROFILE}
 
+        # Load harness via virtual environment
         HARNESS_DIR=$(workspaces.source.path)/harnesses
         source ${HARNESS_DIR}/${HARNESS}.venv/bin/activate
 
         # run inference-perf
         export HF_TOKEN=$(cat "$(workspaces.hf-credentials.path)/HF_TOKEN")
         inference-perf --config_file "$(realpath ${WORKLOAD_PROFILE})" > >(tee -a ${RESULTS_DIR}/stdout.log) 2> >(tee -a ${RESULTS_DIR}/stderr.log >&2)
-        export LLMDBENCH_RUN_EXPERIMENT_HARNESS_RC=$?
+        export RC=$?
 
         # If benchmark harness returned with an error, exit here
-        if [[ $LLMDBENCH_RUN_EXPERIMENT_HARNESS_RC -ne 0 ]]; then
-          echo "❌ Harness returned with error $LLMDBENCH_RUN_EXPERIMENT_HARNESS_RC"
-          exit $LLMDBENCH_RUN_EXPERIMENT_HARNESS_RC
+        if [[ $RC -ne 0 ]]; then
+          echo "❌ Harness returned with error $RC"
+          exit $RC
         fi
         echo "✅ Harness completed successfully."
